name: Update TOC

on:
  push:
    paths:
      - '**/*.md'
      - '!README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update TOC
        run: |
          npm install -g markdown-toc
          markdown-toc -i README.md
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "docs: update TOC"
          file_pattern: README.md
